---
- name: installa pacchetti
  apt: name={{item}} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - glusterfs-server

- name: Verifica init script per glusterfs
  stat: path=/etc/init.d/glusterfs-server
  register: rimuovi_init_gluster

- name: Rinomina init gluster
  command: "{{ item }}"
  when: rimuovi_init_gluster.stat.exists
  notify: reload systemd
  ignore_errors: yes
  with_items:
  - /etc/init.d/glusterfs-server stop
  - killall glusterd 
  - mv /etc/init.d/glusterfs-server /etc/init.d/BCKglusterfs-server

- name: Copia del service
  copy: src=glusterfs/glusterd.service dest=/etc/systemd/system/glusterd.service mode=0644
  notify: reload systemd

- name: Copia del service per mount condiviso
  copy: src=glusterfs/mnt-cluster.service dest=/etc/systemd/system/mnt-cluster.service mode=0644
  notify: reload systemd

- name: Copia dello script che monta
  copy: src=glusterfs/mount-mnt_cluster.sh dest=/usr/local/bin/mount-mnt_cluster.sh mode=0755
  notify: reload systemd

- name: abilita il mount condiviso
  systemd:
    name: mnt-cluster.service
    enabled: yes
    masked: no

- meta: flush_handlers

- name: Servizio Gluster attivo
  service: name=glusterd state=started enabled=yes

- name: Mount USB per brick gluster
  mount:
    path: /mnt/disk-usb1
    fstype: ext4
    src: /dev/sda1
    state: mounted

- name: Creazione del mountpoint
  file: path=/mnt/cluster state=directory
# TODO togliere attributi se brick gia' usato      
#setfattr -x trusted.glusterfs.volume-id $brick_path
#setfattr -x trusted.gfid $brick_path
#rm -rf $brick_path/.glusterfs
#TODO se viene fatto il probe contemporaneamente fallisce.
- name: create gluster volume
  gluster_volume:
    state: present
    name: main-cluster
    bricks: /mnt/disk-usb1/vol
    replicas: "{{play_hosts|length}}"
    cluster: "{{play_hosts}}"

- name: monta il mount condiviso
  systemd:
    name: mnt-cluster.service
    state: started
